### ISSUE TITLE
Add localisation support

### ISSUE THREAD

**Issue by Harjot1Singh** [ManpreetSL/habit-tracker#45]
## Summary

We'd like the app to work in different languages, eventually, so that SHIFT will be accessible to multiple audiences.

To set this up, we need to stop hardcoding copy strings in the components themselves, but refer to keys. We should use `react-i18next` for this: https://react.i18next.com/.

## Approach
- [ ] Install i18n support
- [ ] Initialise i18n in `main`, before React app is rendered
- [ ] Move strings to English resource JSON file

**Comment by ManpreetSL** [comment]
Their site also links to this: https://github.com/i18next/next-i18next
Using Next.js?
[Here](https://locize.com/blog/next-i18next/) you'll find a blog post on how to best use [next-i18next](https://github.com/i18next/next-i18next) with [client side translation download](https://github.com/i18next/next-i18next#client-side-loading-of-translations-via-http) and SEO optimization.

Thoughts? @Harjot1Singh
